### ISSUE TITLE
Amazing, Would Love Typewriter Sounds (Ala Tickkeys)

### ISSUE THREAD

**Issue by voltaireodactyl** [ognistik/alfred-taptix#1]
EDIT: never mind, read the wrong page and didn't see custom paths are already available 🤦‍♂️. Thanks again!

Hey, great work, loving this workflow and the responsiveness is fantastic. Any chance you could add Typewriter sounds like Tickkeys? For some reason the return carriage sound for enter just makes my brain happy. Or if you have a way to add custom sounds let me know, I'm happy to do the legwork!

**Comment by voltaireodactyl** [comment]
read the wrong page and didn't see custom paths are already available 🤦‍♂️. Thanks again!

**Comment by ognistik** [comment]
Glad you figured this out and and I'm happy to know you found this workflow useful!
